package ic3.analyticsops.restapi.reply.schema;

public enum AORestApiSchemaLoadStatus
{
    NOP,
    UNLOADED,
    LOADED,
    DUPLICATED_LOADING_CANCELLED,
    WAITING_LOADING_CANCELLED,
    LOAD_ERROR,
    INCREMENTAL_LOADED,
    INCREMENTAL_LOAD_DEACTIVATED,
    INCREMENTAL_LOAD_ERROR,
    PARTITIONS_UNLOADED,
    PARTITIONS_LOADED,
    PARTITIONS_LOAD_FAILED,
    PARTITIONS_LOAD_ERROR,
}
